#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 30 17:18:36 2026

@author: frocha
"""

title: Felipe Rocha
email: felipe@example.com
description: > 
  Computational Mechanics | Finite Element Methods | Nonlinear Mechanics
baseurl: "" # leave empty for user site
url: "https://felipefr.github.io"
theme: minima
plugins: []